### PR TITLE
Resolve symlinks for PHPCS output

### LINKED ISSUE #293: Doesn't show any error, warning or info
Hey guys, sorry if I'm doing something wrong, but I couldn't make linter-phpcs show any error on atom. phpcs on terminal shows me what it should, but in atom it is just always 0 warning, 0 errors. Can you help me, please?

`phpcs --version` gives me
`PHP_CodeSniffer version 3.1.0 (stable) by Squiz (http://www.squiz.net)`
as well as `/home/user/.composer/vendor/bin/phpcs --version`.

_Linter: Debug_ on _Command Pallete_ shows the following:
```
Platform: linux
Atom Version: 1.20.1
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - PHPCS
Disabled Linter Providers: 
Standard Linter Providers: 
  - CSSLint
  - PHPCS
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - text.html.php
  - meta.embedded.block.php
  - source.php
  - variable.other.php
```
Console on develop tools gives me nothing and busy-signal blinks as it should do.

My configs:
Exec path: `/home/elia/.composer/vendor/bin/phpcs`
`Search for exec` marked
Code standard: `PSR2` (tested with others without sucess)
`Disable when no config file` unmarked
`Search for configuration files` marked (I've tested with and wo conf files)
Tab width: `4`
`Show source` marked

I've installed CSSLint for testing purposes and it works.

### PR DESCRIPTION
**Pull request by EliaBR**
Problem solved:
- `textEditor.getPath()` returns path with symbolic link;
- PHPCS returns its messages indexed by file real path;
This commit creates a `fileRealPath` variable and search for it into data.files.

Fixes #293.

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -313,10 +313,11 @@ export default {
 
         let messages;
         if (semver.gte(version, '2.0.0')) {
-          if (!data.files[filePath]) {
+          let fileRealPath = fs.realpathSync(filePath);
```
Comment (Arcanemagus) [inline lib/main.js]: Several things wrong here:

- You haven't brought in `fs`
- `fileRealPath` isn't changed, used `const`
- Don't use the `Sync` method, create a small `async` wrapper and use the correct version.

**Comment by Arcanemagus** [comment]
It looks like this has probably been an issue since Atom v1.14.0 (https://github.com/atom/atom/pull/13545).

File: lib/main.js (hunk 1 above)
Comment (Arcanemagus) [reply lib/main.js]: An example of the wrapper function would be something like [this](https://github.com/AtomLinter/linter-jshint/blob/0bf7818f9098d451f674ec273611083b39798032/lib/helpers.js#L63-L71).

Comment (EliaBR) [reply lib/main.js]: Thanks @Arcanemagus, I'll do that ASAP. I'm a beginner at this, so could you tell me how to bring `fs`? As I understand it should be treated as semver, minimatch, helpers and path, right? But what should I require?

I'll have to study how to change code and continue with this in the same PR, but I guess it isn't difficult :)

Comment (Arcanemagus) [reply lib/main.js]: > how to bring fs? As I understand it should be treated as semver, minimatch, helpers and path, right?

Exactly, create a variable to act as a placeholder, and then in the `loadDeps` bring it in with `fs = requires('fs');`.
